//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHOP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShopEntities : DbContext
    {
        private static ShopEntities _instance;
        public ShopEntities()
            : base("name=ShopEntities")
        {
        }

        public static ShopEntities GetContext()
        {
            if (_instance == null)
                _instance = new ShopEntities();
            return _instance;
        }
        
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Заказ> Заказ { get; set; }
        public virtual DbSet<Заметки> Заметки { get; set; }
        public virtual DbSet<Клиенты> Клиенты { get; set; }
        public virtual DbSet<Пользователи> Пользователи { get; set; }
        public virtual DbSet<Поставщик> Поставщик { get; set; }
        public virtual DbSet<СтепеньВажности> СтепеньВажности { get; set; }
        public virtual DbSet<Тип_оплаты> Тип_оплаты { get; set; }
        public virtual DbSet<Товар> Товар { get; set; }
    }
}
