//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заметки
    {
        public int IdЗаметки { get; set; }
        public string Заголовок { get; set; }
        public string Описание { get; set; }
        public Nullable<int> КодВажности { get; set; }
    
        public virtual СтепеньВажности СтепеньВажности { get; set; }
    }
}
