//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ
    {
        public int КодЗаказа { get; set; }
        public Nullable<System.DateTime> ДатаЗаказа { get; set; }
        public Nullable<System.DateTime> ДатаИсполнения { get; set; }
        public Nullable<int> КодТовара { get; set; }
        public Nullable<int> Оплата { get; set; }
        public Nullable<int> КодКлиента { get; set; }
        public Nullable<int> КодПоставщика { get; set; }
    
        public virtual Клиенты Клиенты { get; set; }
        public virtual Поставщик Поставщик { get; set; }
        public virtual Тип_оплаты Тип_оплаты { get; set; }
        public virtual Товар Товар { get; set; }
    }
}
