//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class СтепеньВажности
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public СтепеньВажности()
        {
            this.Заметки = new HashSet<Заметки>();
        }
    
        public int Id { get; set; }
        public string Наименование { get; set; }
        public byte[] Картинка { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заметки> Заметки { get; set; }
    }
}
