//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Тип_оплаты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Тип_оплаты()
        {
            this.Заказ = new HashSet<Заказ>();
        }
    
        public int КодОплаты { get; set; }
        public string НазваниеБанка { get; set; }
        public int НомерСчета { get; set; }
        public Nullable<int> КодКлиента { get; set; }
        public Nullable<int> Сумма { get; set; }
        public Nullable<int> КодТовара { get; set; }
        public Nullable<int> Количество { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заказ> Заказ { get; set; }
        public virtual Клиенты Клиенты { get; set; }
    }
}
